
package edu.softserveinc.healthbody.webclient.api;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HealthBodyService", targetNamespace = "http://webservice.healthbody.softserveinc.edu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HealthBodyService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "createUser", targetNamespace = "http://webservice.healthbody.softserveinc.edu/", className = "edu.softserveinc.healthbody.webclient.api.CreateUser")
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://webservice.healthbody.softserveinc.edu/", className = "edu.softserveinc.healthbody.webclient.api.CreateUserResponse")
    @Action(input = "http://webservice.healthbody.softserveinc.edu/HealthBodyService/createUserRequest", output = "http://webservice.healthbody.softserveinc.edu/HealthBodyService/createUserResponse")
    public void createUser(
        @WebParam(name = "arg0", targetNamespace = "")
        UserDTO arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<edu.softserveinc.healthbody.webclient.api.CompetitionDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllCompetitions", targetNamespace = "http://webservice.healthbody.softserveinc.edu/", className = "edu.softserveinc.healthbody.webclient.api.GetAllCompetitions")
    @ResponseWrapper(localName = "getAllCompetitionsResponse", targetNamespace = "http://webservice.healthbody.softserveinc.edu/", className = "edu.softserveinc.healthbody.webclient.api.GetAllCompetitionsResponse")
    @Action(input = "http://webservice.healthbody.softserveinc.edu/HealthBodyService/getAllCompetitionsRequest", output = "http://webservice.healthbody.softserveinc.edu/HealthBodyService/getAllCompetitionsResponse")
    public List<CompetitionDTO> getAllCompetitions(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<edu.softserveinc.healthbody.webclient.api.UserDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllUserstoAddInCompetition", targetNamespace = "http://webservice.healthbody.softserveinc.edu/", className = "edu.softserveinc.healthbody.webclient.api.GetAllUserstoAddInCompetition")
    @ResponseWrapper(localName = "getAllUserstoAddInCompetitionResponse", targetNamespace = "http://webservice.healthbody.softserveinc.edu/", className = "edu.softserveinc.healthbody.webclient.api.GetAllUserstoAddInCompetitionResponse")
    @Action(input = "http://webservice.healthbody.softserveinc.edu/HealthBodyService/getAllUserstoAddInCompetitionRequest", output = "http://webservice.healthbody.softserveinc.edu/HealthBodyService/getAllUserstoAddInCompetitionResponse")
    public List<UserDTO> getAllUserstoAddInCompetition(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "createCompetition", targetNamespace = "http://webservice.healthbody.softserveinc.edu/", className = "edu.softserveinc.healthbody.webclient.api.CreateCompetition")
    @ResponseWrapper(localName = "createCompetitionResponse", targetNamespace = "http://webservice.healthbody.softserveinc.edu/", className = "edu.softserveinc.healthbody.webclient.api.CreateCompetitionResponse")
    @Action(input = "http://webservice.healthbody.softserveinc.edu/HealthBodyService/createCompetitionRequest", output = "http://webservice.healthbody.softserveinc.edu/HealthBodyService/createCompetitionResponse")
    public void createCompetition(
        @WebParam(name = "arg0", targetNamespace = "")
        CompetitionDTO arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<edu.softserveinc.healthbody.webclient.api.CompetitionDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllActiveCompetitionsByUser", targetNamespace = "http://webservice.healthbody.softserveinc.edu/", className = "edu.softserveinc.healthbody.webclient.api.GetAllActiveCompetitionsByUser")
    @ResponseWrapper(localName = "getAllActiveCompetitionsByUserResponse", targetNamespace = "http://webservice.healthbody.softserveinc.edu/", className = "edu.softserveinc.healthbody.webclient.api.GetAllActiveCompetitionsByUserResponse")
    @Action(input = "http://webservice.healthbody.softserveinc.edu/HealthBodyService/getAllActiveCompetitionsByUserRequest", output = "http://webservice.healthbody.softserveinc.edu/HealthBodyService/getAllActiveCompetitionsByUserResponse")
    public List<CompetitionDTO> getAllActiveCompetitionsByUser(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<edu.softserveinc.healthbody.webclient.api.UserDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllUsersinCompetition", targetNamespace = "http://webservice.healthbody.softserveinc.edu/", className = "edu.softserveinc.healthbody.webclient.api.GetAllUsersinCompetition")
    @ResponseWrapper(localName = "getAllUsersinCompetitionResponse", targetNamespace = "http://webservice.healthbody.softserveinc.edu/", className = "edu.softserveinc.healthbody.webclient.api.GetAllUsersinCompetitionResponse")
    @Action(input = "http://webservice.healthbody.softserveinc.edu/HealthBodyService/getAllUsersinCompetitionRequest", output = "http://webservice.healthbody.softserveinc.edu/HealthBodyService/getAllUsersinCompetitionResponse")
    public List<UserDTO> getAllUsersinCompetition(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDescriptionOfGroup", targetNamespace = "http://webservice.healthbody.softserveinc.edu/", className = "edu.softserveinc.healthbody.webclient.api.GetDescriptionOfGroup")
    @ResponseWrapper(localName = "getDescriptionOfGroupResponse", targetNamespace = "http://webservice.healthbody.softserveinc.edu/", className = "edu.softserveinc.healthbody.webclient.api.GetDescriptionOfGroupResponse")
    @Action(input = "http://webservice.healthbody.softserveinc.edu/HealthBodyService/getDescriptionOfGroupRequest", output = "http://webservice.healthbody.softserveinc.edu/HealthBodyService/getDescriptionOfGroupResponse")
    public String getDescriptionOfGroup(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<edu.softserveinc.healthbody.webclient.api.CompetitionDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllActiveCompetitions", targetNamespace = "http://webservice.healthbody.softserveinc.edu/", className = "edu.softserveinc.healthbody.webclient.api.GetAllActiveCompetitions")
    @ResponseWrapper(localName = "getAllActiveCompetitionsResponse", targetNamespace = "http://webservice.healthbody.softserveinc.edu/", className = "edu.softserveinc.healthbody.webclient.api.GetAllActiveCompetitionsResponse")
    @Action(input = "http://webservice.healthbody.softserveinc.edu/HealthBodyService/getAllActiveCompetitionsRequest", output = "http://webservice.healthbody.softserveinc.edu/HealthBodyService/getAllActiveCompetitionsResponse")
    public List<CompetitionDTO> getAllActiveCompetitions(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<edu.softserveinc.healthbody.webclient.api.CompetitionDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllCompetitionsByUser", targetNamespace = "http://webservice.healthbody.softserveinc.edu/", className = "edu.softserveinc.healthbody.webclient.api.GetAllCompetitionsByUser")
    @ResponseWrapper(localName = "getAllCompetitionsByUserResponse", targetNamespace = "http://webservice.healthbody.softserveinc.edu/", className = "edu.softserveinc.healthbody.webclient.api.GetAllCompetitionsByUserResponse")
    @Action(input = "http://webservice.healthbody.softserveinc.edu/HealthBodyService/getAllCompetitionsByUserRequest", output = "http://webservice.healthbody.softserveinc.edu/HealthBodyService/getAllCompetitionsByUserResponse")
    public List<CompetitionDTO> getAllCompetitionsByUser(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateUser", targetNamespace = "http://webservice.healthbody.softserveinc.edu/", className = "edu.softserveinc.healthbody.webclient.api.UpdateUser")
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://webservice.healthbody.softserveinc.edu/", className = "edu.softserveinc.healthbody.webclient.api.UpdateUserResponse")
    @Action(input = "http://webservice.healthbody.softserveinc.edu/HealthBodyService/updateUserRequest", output = "http://webservice.healthbody.softserveinc.edu/HealthBodyService/updateUserResponse")
    public void updateUser(
        @WebParam(name = "arg0", targetNamespace = "")
        UserDTO arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "lockUser", targetNamespace = "http://webservice.healthbody.softserveinc.edu/", className = "edu.softserveinc.healthbody.webclient.api.LockUser")
    @ResponseWrapper(localName = "lockUserResponse", targetNamespace = "http://webservice.healthbody.softserveinc.edu/", className = "edu.softserveinc.healthbody.webclient.api.LockUserResponse")
    @Action(input = "http://webservice.healthbody.softserveinc.edu/HealthBodyService/lockUserRequest", output = "http://webservice.healthbody.softserveinc.edu/HealthBodyService/lockUserResponse")
    public void lockUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        boolean arg1);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateGroup", targetNamespace = "http://webservice.healthbody.softserveinc.edu/", className = "edu.softserveinc.healthbody.webclient.api.UpdateGroup")
    @ResponseWrapper(localName = "updateGroupResponse", targetNamespace = "http://webservice.healthbody.softserveinc.edu/", className = "edu.softserveinc.healthbody.webclient.api.UpdateGroupResponse")
    @Action(input = "http://webservice.healthbody.softserveinc.edu/HealthBodyService/updateGroupRequest", output = "http://webservice.healthbody.softserveinc.edu/HealthBodyService/updateGroupResponse")
    public void updateGroup(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<edu.softserveinc.healthbody.webclient.api.GroupDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllGroups", targetNamespace = "http://webservice.healthbody.softserveinc.edu/", className = "edu.softserveinc.healthbody.webclient.api.GetAllGroups")
    @ResponseWrapper(localName = "getAllGroupsResponse", targetNamespace = "http://webservice.healthbody.softserveinc.edu/", className = "edu.softserveinc.healthbody.webclient.api.GetAllGroupsResponse")
    @Action(input = "http://webservice.healthbody.softserveinc.edu/HealthBodyService/getAllGroupsRequest", output = "http://webservice.healthbody.softserveinc.edu/HealthBodyService/getAllGroupsResponse")
    public List<GroupDTO> getAllGroups(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns edu.softserveinc.healthbody.webclient.api.UserDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserByLogin", targetNamespace = "http://webservice.healthbody.softserveinc.edu/", className = "edu.softserveinc.healthbody.webclient.api.GetUserByLogin")
    @ResponseWrapper(localName = "getUserByLoginResponse", targetNamespace = "http://webservice.healthbody.softserveinc.edu/", className = "edu.softserveinc.healthbody.webclient.api.GetUserByLoginResponse")
    @Action(input = "http://webservice.healthbody.softserveinc.edu/HealthBodyService/getUserByLoginRequest", output = "http://webservice.healthbody.softserveinc.edu/HealthBodyService/getUserByLoginResponse")
    public UserDTO getUserByLogin(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns edu.softserveinc.healthbody.webclient.api.GroupDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGroupByName", targetNamespace = "http://webservice.healthbody.softserveinc.edu/", className = "edu.softserveinc.healthbody.webclient.api.GetGroupByName")
    @ResponseWrapper(localName = "getGroupByNameResponse", targetNamespace = "http://webservice.healthbody.softserveinc.edu/", className = "edu.softserveinc.healthbody.webclient.api.GetGroupByNameResponse")
    @Action(input = "http://webservice.healthbody.softserveinc.edu/HealthBodyService/getGroupByNameRequest", output = "http://webservice.healthbody.softserveinc.edu/HealthBodyService/getGroupByNameResponse")
    public GroupDTO getGroupByName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<edu.softserveinc.healthbody.webclient.api.UserDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllUsers", targetNamespace = "http://webservice.healthbody.softserveinc.edu/", className = "edu.softserveinc.healthbody.webclient.api.GetAllUsers")
    @ResponseWrapper(localName = "getAllUsersResponse", targetNamespace = "http://webservice.healthbody.softserveinc.edu/", className = "edu.softserveinc.healthbody.webclient.api.GetAllUsersResponse")
    @Action(input = "http://webservice.healthbody.softserveinc.edu/HealthBodyService/getAllUsersRequest", output = "http://webservice.healthbody.softserveinc.edu/HealthBodyService/getAllUsersResponse")
    public List<UserDTO> getAllUsers(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
